name: 'git-retest-checkup-action'
description: 'This action checks whether a retest is needed after Pull request merged into base branch.'
author: Zvi Grinberg

inputs:
  base-ref:  # id of input
    description: 'base ref commit branch, tag or sha digest, usually the upstream main branch'
    required: true
    default: 'HEAD'
  pr-ref:  # id of input
    description: 'head ref commit branch, tag or sha digest, usually a PR head branch'
    required: true
    default: 'HEAD'
  file-pattern-regex:
    required: false
    description: 'the pattern of the changed files (in the difference between branches ) that will affect the result of if re-test is needed , if at least one changed file matches the pattern, then it will return result true, if empty then any change will return result true.'
    default: ''

outputs:
  retest-is-needed:
    description: "Returns true if retest is needed, otherwise, returns false"
    value: ${{ steps.check-if-retest-needed-final.outputs.result }}
runs:
  using: "composite"
  steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check if retest is needed
        id: check-if-retest-needed
        run: $GITHUB_ACTION_PATH/is-retest-needed.sh
        shell: bash
        env:
          BASE_BRANCH: ${{ inputs.base-ref }}
          HEAD_BRANCH: ${{ inputs.pr-ref }}
          GITHUB_ACTION_PATH: ${{ github.action_path }}
          GITHUB_REPOSITORY: ${{ github.workspace }}

      - name: Check if changed files
        if:
        id: check-if-retest-needed-final
        run: python $GITHUB_ACTION_PATH/check_changed_files.py
        shell: bash
        env:
          FILE_PATTERN_REGEX: ${{ inputs.file-pattern-regex }}
          GITHUB_ACTION_PATH: ${{ github.action_path }}
          GITHUB_REPOSITORY: ${{ github.workspace }}



